apiVersion: v1
kind: ReplicationController
metadata:
  name: boilerplate
  labels:
    name: boilerplate
spec:
  replicas: 1
  selector:
    name: boilerplate
  template:
    metadata:
      labels:
        name: boilerplate
    spec:
      containers:
        - name: boilerplate
          image: gcr.io/yebo-project/boilerplate:latest
          ports:
            - containerPort: 443
            - containerPort: 80
          env:
            - name: IS_FUN
              value: true
          volumeMounts:
            - mountPath: /usr/local/data
              name: data
      volumes:
        - name: data
          gcePersistentDisk:
            pdName: boilerplate-disk
            fsType: ext4
        - name: logs
          emptyDir: {}



