apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: $NAME
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: $NAME
    spec:
      containers:
        - name: $NAME
          image: "gcr.io/yebo-project/$NAME:latest"
          lifecycle:
            preStop:
              exec:
                command: ["/usr/sbin/nginx","-s","quit"]
          volumeMounts:
            - name: "nginx-conf"
              mountPath: "/etc/nginx/conf.d"
            - name: "tls-$NAME-certs"
              mountPath: "/etc/tls"
      volumes:
        # This has to be created before hand
        - name: "nginx-conf"
          configMap:
            name: "nginx-conf"
            items:
              - key: "proxy.conf"
                path: "proxy.conf"
        - name: "tls-$NAME-certs"
          secret:
            secretName: "tls-$NAME-certs"

